Repository kimgunwooo/FQS-flexible-queue-service, pull requests merged in 2024-10, with the labels that each got.

#8 Feat/5, 6 kafka setting
  docker-compose.yml
  service/queue/build.gradle
  service/queue/src/main/java/com/f4/fqs/queue/kafka/config/KafkaConfig.java
  service/queue/src/main/java/com/f4/fqs/queue/kafka/consumer/ClientConsumerConfig.java
  service/queue/src/main/java/com/f4/fqs/queue/kafka/consumer/EventSourcingConsumerConfig.java
  service/queue/src/main/java/com/f4/fqs/queue/kafka/producer/ClientProducerConfig.java
  service/queue/src/main/java/com/f4/fqs/queue/kafka/producer/EventSourcingProducerConfig.java
  service/queue/src/main/resources/application.yml
Labels: setting

#11 Feat/5 gateway setting
  service/gateway/build.gradle
  service/gateway/src/main/java/com/f4/fqs/gateway/application/dto/UserDto.java
  service/gateway/src/main/java/com/f4/fqs/gateway/application/service/RedisService.java
  service/gateway/src/main/java/com/f4/fqs/gateway/config/CacheConfig.java
  service/gateway/src/main/java/com/f4/fqs/gateway/config/RedisConfig.java
  service/gateway/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
  service/gateway/src/main/resources/application.yml
Labels: feat, setting

#10 [#7] queue server settting
  build.gradle
  docker-compose.yml
  service/queue/build.gradle
  service/queue/src/main/java/com/f4/fqs/queue/application/response/CreateQueueResponse.java
  service/queue/src/main/java/com/f4/fqs/queue/application/service/QueueService.java
  service/queue/src/main/java/com/f4/fqs/queue/domain/model/Queue.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/config/R2dbcConfig.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/repository/QueueRepository.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/controller/QueueController.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/request/CreateQueueRequest.java
  service/queue/src/main/resources/application.yml
  service/queue/src/main/resources/schema.sql
  service/queue/src/test/java/com/f4/fqs/queue/infrastructure/repository/QueueRepositoryTest.java
  service/queue/src/test/resources/application-test.yml
Labels: feat, setting

#9 Feat/4 log in sign up
  service/auth/build.gradle
  service/auth/src/main/java/com/f4/fqs/auth/AuthApplication.java
  service/auth/src/main/java/com/f4/fqs/auth/client/UserServiceClient.java
  service/auth/src/main/java/com/f4/fqs/auth/config/SecurityConfig.java
  service/auth/src/main/java/com/f4/fqs/auth/controller/AuthController.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/LogInRequestDto.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/SignUpRequestDto.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/UserDto.java
  service/auth/src/main/java/com/f4/fqs/auth/jwt/JwtAuthenticationFilter.java
  service/auth/src/main/java/com/f4/fqs/auth/jwt/JwtUtil.java
  service/auth/src/main/java/com/f4/fqs/auth/service/AuthService.java
  service/auth/src/main/resources/application.yml
  service/user/build.gradle
  service/user/src/main/java/com/f4/fqs/user/UserApplication.java
  service/user/src/main/java/com/f4/fqs/user/config/EncoderConfig.java
  service/user/src/main/java/com/f4/fqs/user/controller/UserController.java
  service/user/src/main/java/com/f4/fqs/user/dto/LogInRequestDto.java
  service/user/src/main/java/com/f4/fqs/user/dto/SignUpRequestDto.java
  service/user/src/main/java/com/f4/fqs/user/dto/UserDto.java
  service/user/src/main/java/com/f4/fqs/user/model/User.java
  service/user/src/main/java/com/f4/fqs/user/repository/UserRepository.java
  service/user/src/main/java/com/f4/fqs/user/service/UserService.java
Labels: feat

#12 chore : queue server mysql schema 수정
  service/queue/src/main/resources/schema.sql
Labels: setting

#17 Feat/5 gateway
  service/gateway/src/main/java/com/f4/fqs/gateway/application/dto/UserDto.java
  service/gateway/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
Labels: bug, refactor, setting

#19 Feat/13 queue server redis
  docker-compose.yml
  service/queue/build.gradle
  service/queue/src/main/java/com/f4/fqs/queue/application/response/QueueBeanInfo.java
  service/queue/src/main/java/com/f4/fqs/queue/application/service/QueueBeanService.java
  service/queue/src/main/java/com/f4/fqs/queue/application/service/QueuePackageService.java
  service/queue/src/main/java/com/f4/fqs/queue/application/service/QueueService.java
  service/queue/src/main/java/com/f4/fqs/queue/domain/model/Queue.java
  service/queue/src/main/java/com/f4/fqs/queue/domain/model/QueueBean.java
  service/queue/src/main/java/com/f4/fqs/queue/domain/model/QueuePackage.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/aop/AuthorizationAspect.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/aop/AuthorizationRequired.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/config/RedisConfig.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/repository/QueueBeanRepository.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/repository/QueuePackageRepository.java
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/repository/QueueRepository.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/controller/QueueController.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/exception/GlobalExceptionHandler.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/exception/QueueErrorCode.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/request/CreateQueueRequest.java
  service/queue/src/main/resources/application.yml
  service/queue/src/main/resources/data.sql
  service/queue/src/main/resources/schema.sql
  service/queue/src/test/java/com/f4/fqs/queue/infrastructure/aop/AuthorizationAspectTest.java
  service/queue/src/test/java/com/f4/fqs/queue/infrastructure/repository/QueueRepositoryTest.java
Labels: feat, setting

#22 Feat/21 queue manage server crud
  service/queue_manage/build.gradle
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/QueueManageApplication.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/response/CloseQueueResponse.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/response/CreateQueueResponse.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/response/UpdateQueueExpirationTimeResponse.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/QueueInfo.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/QueueService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/domain/model/BaseEntity.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/domain/model/Queue.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/aop/AuthorizationAspect.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/aop/AuthorizationRequired.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/config/JpaConfig.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/config/RedisConfig.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/repository/QueueRepository.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/controller/QueueController.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/exception/GlobalExceptionHandler.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/exception/QueueErrorCode.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/request/CreateQueueRequest.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/request/UpdateExpirationTimeRequest.java
  service/queue_manage/src/main/resources/application.yml
  service/queue_manage/src/test/java/com/f4/fqs/queue_manage/QueueManageApplicationTests.java
  settings.gradle
Labels: feat, setting

#29 Feat/15 user crud
  service/auth/build.gradle
  service/auth/src/main/java/com/f4/fqs/auth/GlobalExceptionHandler.java
  service/auth/src/main/java/com/f4/fqs/auth/UserRoleEnum.java
  service/auth/src/main/java/com/f4/fqs/auth/client/UserServiceClient.java
  service/auth/src/main/java/com/f4/fqs/auth/config/SecurityConfig.java
  service/auth/src/main/java/com/f4/fqs/auth/controller/AuthController.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/IAM/CreateAccountRequest.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/IAM/IAMUserDto.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/IAM/LogInIAMRequestDto.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/ROOT/LogInRequestDto.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/ROOT/RootUserDto.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/ROOT/SignUpRequestDto.java
  service/auth/src/main/java/com/f4/fqs/auth/dto/UserDto.java
  service/auth/src/main/java/com/f4/fqs/auth/jwt/JwtAuthentication.java
  service/auth/src/main/java/com/f4/fqs/auth/jwt/JwtAuthenticationFilter.java
  service/auth/src/main/java/com/f4/fqs/auth/jwt/JwtUtil.java
  service/auth/src/main/java/com/f4/fqs/auth/service/AuthService.java
  service/user/build.gradle
  service/user/src/main/java/com/f4/fqs/user/controller/UserController.java
  service/user/src/main/java/com/f4/fqs/user/dto/IAM/CreateAccountRequest.java
  service/user/src/main/java/com/f4/fqs/user/dto/IAM/IAMUserDto.java
  service/user/src/main/java/com/f4/fqs/user/dto/IAM/LogInIAMRequestDto.java
  service/user/src/main/java/com/f4/fqs/user/dto/ROOT/LogInRequestDto.java
  service/user/src/main/java/com/f4/fqs/user/dto/ROOT/RootUserDto.java
  service/user/src/main/java/com/f4/fqs/user/dto/ROOT/SignUpRequestDto.java
  service/user/src/main/java/com/f4/fqs/user/dto/UserDto.java
  service/user/src/main/java/com/f4/fqs/user/model/IAMUser.java
  service/user/src/main/java/com/f4/fqs/user/model/RootUser.java
  service/user/src/main/java/com/f4/fqs/user/model/UserRoleEnum.java
  service/user/src/main/java/com/f4/fqs/user/repository/IAMRepository.java
  service/user/src/main/java/com/f4/fqs/user/repository/UserRepository.java
  service/user/src/main/java/com/f4/fqs/user/service/UserService.java
  service/user/src/test/java/com/f4/fqs/user/RootUserApplicationTests.java
Labels: feat, refactor

#31 add : 인스턴스 동적 생성 기능추가
  service/queue_manage/build.gradle
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/PortManager.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/QueueService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/domain/model/Queue.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/docker/DockerService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/exception/QueueErrorCode.java
  service/queue_manage/src/main/resources/docker-compose.yml
Labels: feat

#37 hotfix : gateway-authorize-active
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/application/service/RedisService.java
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
Labels: setting

#38 Feat/35 queue manage route and env
  service/gateway/gateway_domain/src/main/java/com/f4/fqs/gateway_domain/domain/ApiRoute.java
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/application/service/impl/ApiRouteLocatorImpl.java
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/application/service/impl/RouteServiceImpl.java
  service/queue_manage/build.gradle
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/response/QueueInfo.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/QueueService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/docker/DockerService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/controller/QueueController.java
Labels: feat, setting

#39 Feat/gateway auth logic
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/application/service/RedisService.java
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/RedisConfig.java
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
  service/gateway/gateway_server/src/main/resources/application.yml
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/infrastructure/docker/DockerService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/request/CreateQueueRequest.java
Labels: bug, feat, refactor

#41 refector : gateway-authorize-logic
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
Labels: refactor

#45 hotfix : queue-validation-per-logic
  service/event_store/src/main/resources/schema.sql
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
  service/gateway/gateway_server/src/main/resources/application.yml
  service/queue/src/main/java/com/f4/fqs/queue/presentation/controller/QueueController.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/exception/QueueErrorCode.java
  service/queue_manage/src/main/resources/docker-compose.yml
Labels: bug, feat, refactor

#47 fix : add validation on queue service with secretKey
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/application/service/RedisService.java
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
Labels: feat, refactor, perf

#51 hotfix : queue_server redis 할당 수정 및 대기열 생성 시 음수값 할당 수정
  service/queue/src/main/resources/application-dev.yml
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/request/CreateQueueRequest.java
Labels: bug

#50 #49 add validation about queue name
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/controller/QueueController.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/exception/QueueErrorCode.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/request/CreateQueueRequest.java
Labels: feat

#53 feat : refector/52-authorization-separate-jwt-and-secretKey and add throw…
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
Labels: refactor

#56 Feat/54 event producing modulization
  common/kafka/build.gradle
  common/kafka/src/main/java/com/f4/fqs/commons/kafka/config/ComponentScanConfig.java
  common/kafka/src/main/java/com/f4/fqs/commons/kafka/config/KafkaConfig.java
  common/kafka/src/main/java/com/f4/fqs/commons/kafka/producer/EventProducerService.java
  common/kafka/src/main/java/com/f4/fqs/commons/kafka/producer/EventSourcingExecutor.java
  common/kafka/src/main/java/com/f4/fqs/commons/kafka/producer/ProducerService.java
  common/kafka/src/test/java/com/f4/fqs/commons/domain/DomainApplicationTests.java
  common/kafka_common/build.gradle
  common/kafka_common/src/main/java/com/f4/fqs/commons/kafka_common/exception/BusinessException.java
  common/kafka_common/src/main/java/com/f4/fqs/commons/kafka_common/exception/StoreErrorCode.java
  common/kafka_common/src/main/java/com/f4/fqs/commons/kafka_common/message/EventType.java
  common/kafka_common/src/main/java/com/f4/fqs/commons/kafka_common/message/QueueCommand.java
  common/kafka_common/src/main/java/com/f4/fqs/commons/kafka_common/util/CommonConstraints.java
  common/kafka_common/src/main/java/com/f4/fqs/commons/kafka_common/util/KafkaUtil.java
  common/kafka_common/src/main/java/com/f4/fqs/commons/kafka_common/util/ParsingUtil.java
  common/kafka_common/src/test/java/com/f4/fqs/commons/domain/DomainApplicationTests.java
  common/reactive_kafka/build.gradle
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/config/ComponentScanConfig.java
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/config/KafkaConfig.java
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/producer/EventProducerService.java
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/producer/EventSourcingExecutor.java
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/producer/ProducerService.java
  common/reactive_kafka/src/test/java/com/f4/fqs/commons/domain/DomainApplicationTests.java
  service/event_store/build.gradle
  service/event_store/src/main/java/com/f4/fqs/eventStore/EventStoreApplication.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/config/KafkaConfig.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/service/consumer/EventHandler.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/model/EventTypeToStringConverter.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/model/StringToEventTypeConverter.java
  service/queue/build.gradle
  service/queue/src/main/java/com/f4/fqs/queue/QueueApplication.java
  service/queue/src/main/java/com/f4/fqs/queue/application/service/QueueService.java
  service/queue/src/main/java/com/f4/fqs/queue/redis/service/RedisService.java
  service/queue/src/test/java/com/f4/fqs/queue/infrastructure/repository/RedisServiceTest.java
  service/queue_manage/build.gradle
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/QueueManageApplication.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/KafkaService.java
  service/queue_manage/src/main/resources/application-dev.yml
  service/queue_manage/src/main/resources/application.yml
  service/queue_manage/src/test/java/com/f4/fqs/queue_manage/KafkaTest.java
  service/user/build.gradle
  service/user/src/main/resources/application.yml
  settings.gradle
Labels: refactor, setting

#60 feat : secret key 와 queue 이름의 쌍이 맞는지 검사하는 api 구현
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/QueueService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/controller/QueueController.java
Labels: feat

#61 Feat/30 payment
  service/payment/build.gradle
  service/payment/src/main/java/com/f4/fqs/payment/PaymentController.java
  service/payment/src/main/java/com/f4/fqs/payment/controller/PaymentController.java
  service/payment/src/main/java/com/f4/fqs/payment/domain/Amount.java
  service/payment/src/main/java/com/f4/fqs/payment/domain/Payment.java
  service/payment/src/main/java/com/f4/fqs/payment/dto/PaymentApproveDto.java
  service/payment/src/main/java/com/f4/fqs/payment/dto/PaymentReadyDto.java
  service/payment/src/main/java/com/f4/fqs/payment/dto/PaymentReadyRequest.java
  service/payment/src/main/java/com/f4/fqs/payment/repository/PaymentRepository.java
  service/payment/src/main/java/com/f4/fqs/payment/service/PaymentService.java
  service/payment/src/main/resources/application.yml
  service/payment/src/main/resources/static/index.html
  service/payment/src/main/resources/templates/success.html
Labels: feat

#62 chore : queue, queuemanage - request, response 변경
  service/queue/src/main/java/com/f4/fqs/queue/application/service/QueueService.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/controller/QueueController.java
  service/queue/src/test/java/com/f4/fqs/queue/application/service/QueueServiceTest.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/presentation/controller/QueueController.java
Labels: refactor

#63 Feat/56 replay 구현 완료
  common/kafka/src/main/java/com/f4/fqs/commons/kafka/config/KafkaConfig.java
  common/kafka/src/main/java/com/f4/fqs/commons/kafka/producer/EventProducerService.java
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/config/KafkaConfig.java
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/producer/EventProducerService.java
  common/reactive_kafka/src/main/java/com/f4/fqs/commons/reactive_kafka/kafka/producer/EventSourcingExecutor.java
  service/event_store/build.gradle
  service/event_store/src/main/java/com/f4/fqs/eventStore/EventStoreApplication.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/application/response/QueueStatusResponse.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/infrastructure/config/R2dbcConfig.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/config/CustomJsonDeserializer.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/config/KafkaConfig.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/config/KafkaObjectInitializer.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/config/KafkaStreamsConfig.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/config/ReactiveKafkaConfig.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/consumer/EventHandler.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/exception/CustomDeserializationExceptionHandler.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/kafka/service/consumer/EventHandler.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/model/EventTypeToStringConverter.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/model/QueueSnapShot.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/model/StringToEventTypeConverter.java
  service/event_store/src/main/java/com/f4/fqs/eventStore/presentation/controller/QueueController.java
  service/event_store/src/main/resources/application.yml
  service/event_store/src/test/java/com/f4/fqs/eventStore/kafka/service/consumer/EventHandlerTest.java
  service/event_store/src/test/resources/application-test.yml
  service/queue/src/main/java/com/f4/fqs/queue/infrastructure/config/RedisConfig.java
  service/queue/src/main/java/com/f4/fqs/queue/presentation/controller/QueueController.java
Labels: feat

#66 feat : docs
  README.md
  docker-compose.yml
  our service range.png
Labels: docs

#67 feat : 대기열 생성/삭제 시 event store로 event를 날리는 기능 추가
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/KafkaService.java
  service/queue_manage/src/main/java/com/f4/fqs/queue_manage/application/service/QueueService.java
Labels: feat

#65 Feat/58 monitoring
  prometheus/docker-compose.yml
  prometheus/prometheus.yml
  service/auth/build.gradle
  service/auth/src/main/resources/application.yml
  service/auth/src/main/resources/logback.xml
  service/eureka/build.gradle
  service/eureka/src/main/resources/application.yml
  service/eureka/src/main/resources/logback.xml
  service/event_store/build.gradle
  service/event_store/src/main/resources/application.yml
  service/event_store/src/main/resources/logback.xml
  service/gateway/gateway_domain/build.gradle
  service/gateway/gateway_server/build.gradle
  service/gateway/gateway_server/src/main/java/com/f4/fqs/gateway/config/SecurityConfig.java
  service/gateway/gateway_server/src/main/resources/application.yml
  service/gateway/gateway_server/src/main/resources/logback.xml
  service/payment/build.gradle
  service/payment/src/main/resources/application.yml
  service/payment/src/main/resources/logback.xml
  service/queue/build.gradle
  service/queue/src/main/resources/application.yml
  service/queue/src/main/resources/logback.xml
  service/queue_manage/build.gradle
  service/queue_manage/src/main/resources/application.yml
  service/queue_manage/src/main/resources/logback.xml
  service/user/build.gradle
  service/user/src/main/resources/application.yml
  service/user/src/main/resources/logback.xml
Labels: setting

#74 docs : image 경로를 수정
  README.md
Labels: docs
